### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by zerlix** [Tfarcenim/DropOff#12]
**Issue description:**
If I want to change the priority in refined storage the client crashes

**What happens:**
When I click on Priority the client crashes

**Steps to reproduce:**

1. Connect a external Storage / Disk Drive
2. Open the GUI and click on priority
3. Client Crash

**Version** 
- Minecraft: 1.15.2
- Forge: 31.1.46
- Refined Storage: 1.8.1
- QuickStack: 3.0.3c

**Crashlog and Bug Report (refined storage)**
- https://pastebin.com/S4cujUk6
- https://github.com/raoulvdberge/refinedstorage/issues/2486

**Comment by Tfarcenim** [comment]
yay, another mod that doesn't register it's containers

**Comment by raoulvdberge** [comment]
Rs registers its containers perfectly fine.

**Comment by Tfarcenim** [comment]
No it's not, otherwise it wouldn't be crashing.
![a](https://user-images.githubusercontent.com/44327798/79871719-c3c36000-83b2-11ea-8f77-93a635105fe3.png)
 The crash above is only possible if a container has both a null containertype and it doesn't override getType
