### ISSUE TITLE
[1.15.2] Forge 31.1.46 crash on Horse inventory

### ISSUE THREAD

**Issue by Excaliburning** [Tfarcenim/DropOff#13]
Hi !

When right clicking a horse or opening your inventory while riding a horse, the game crashes instantly.
At first the crash log mentioned something about Optifine's rendering, so I removed it and tested again. This time, Quickstack was incriminated.

[Crashlog right here.](https://gist.github.com/Excaliburning/58665d750a199c03243c6e6b549ce99c)

**Comment by Tfarcenim** [comment]
fixed in 3.0.3c

**Comment by Excaliburning** [comment]
Didn't notice the update, thanks for the fast answer.
