### ISSUE TITLE
Mod does not work with forge 31.1.0 and minecraft 1.15.2

### ISSUE THREAD

**Issue by LeoBeliik** [Tfarcenim/DropOff#2]
Error: 
    DropOff (dropoff) encountered an error during the sided_setup event phase
    Failed to load hierarchy member net/minecraftforge/fml/client/config/GuiButtonExt

Latest.log: https://hastebin.com/gapitequhi.md
Version: quickstack 3.0.0

**Comment by Tfarcenim** [comment]
god dammit forge
