### ISSUE TITLE
Crash when shift right clicking JEI settings button

### ISSUE THREAD

**Issue by SeriousCreeper** [Tfarcenim/DropOff#23]
Heya,

with quickstack installed, if you are in survival mode (it's fine in creative mode), and you shift+right click the config button in JEI, the game crashes. 

Crashlog: https://hastebin.com/tecefoquzu.properties

Shift+right clicking that button usually toggles JEI between cheat and recipe mode. 
This crash only happens when quickstack is installed. 

Cheers,
SC

**Comment by Quipex** [comment]
This is fixed in #20 but it doesn't seem like the mod maintainer has spare time to review and merge... In the meanwhile you can checkout https://github.com/wchen1990/DropOff and compile the mod yourself or ask someone to do that for you

**Comment by SvenParoth** [comment]
Thanks! Unfortunately i need it for a modpack at some point soon, so it needs to be hosted on curseforge. But i guess the mod is MIT so could do that temporarily until it gets officially fixed.

**Comment by SeriousCreeper** [comment]
Thanks! Unfortunately i need it for a modpack at some point soon, so it needs to be hosted on curseforge. But i guess the mod is MIT so could do that temporarily until it gets officially fixed.

**Comment by Tfarcenim** [comment]
Fixed in 5.0.1
