### ISSUE TITLE
Suggestion: Be able to change hex code of favorited items

### ISSUE THREAD

**Issue by Lucipo** [Tfarcenim/DropOff#25]
Simple enough, the yellow chosen for the favorited slot hue is very obtrusive and attention-grabbing, being able to change the hex code of the background color used would be awesome! 
![image](https://user-images.githubusercontent.com/36358294/216735526-12b75c7d-063a-47dd-8dac-192352a5426c.png)

Preferred that, if added, this suggestion were present in a 1.19.2 version of the mod.

**Comment by Tfarcenim** [comment]
implemented in 6.1
