### ISSUE TITLE
Move buttons when wearing Quark Backpack

### ISSUE THREAD

**Issue by NielsPilgaard** [Tfarcenim/DropOff#4]
I would like to request that you check whether the player is wearing a Quark Backpack, and if true, move the buttons up by about 30 pixels (configurable preferably)

The reason I would like this is best described by this picture:
![billede](https://user-images.githubusercontent.com/21295394/77818701-d52b8c00-70d4-11ea-8ebf-db1bb7b93d5f.png)
The orange section is the backpack inventory that is added when the user wears a Backpack

**Comment by TheUntamed** [comment]
This also already happens without the backpack. If Quark is installed the buttons are on top of each other:
![Screenshot_2](https://user-images.githubusercontent.com/48363903/78039181-15596b80-736e-11ea-8bd6-a2d01c7efcf7.jpg)
(The overlaid button is the one from quark)

**Comment by Tfarcenim** [comment]
should be less of an issue now, use the offset buttons to manually tweak position, if that doesn't work open a new issue

**Comment by Tfarcenim** [comment]
hardcoding for every single mod simply isn't possible nor feasable

**Comment by NielsPilgaard** [comment]
True, worth a shot though :P
The offset works, thanks.
